### ISSUE TITLE
https://github.com/bdolenc/ll-test#unit-testing

### ISSUE THREAD

**Issue by jillesca** [bdolenc/ll-test#7]
When running the unit test I got this error. 

I tried to find the issue, I thought it could be the test directory is in the wrong place. but not sure. Using relative paths and env vars can help to make sure the files are in the right place.

```
developer:src > cd ~/src/loopback/src/
developer:src > python -m unittest discover --start-directory ../python/tests --top-level-directory ../python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/usr/local/lib/python3.11/unittest/main.py", line 101, in __init__
    self.parseArgs(argv)
  File "/usr/local/lib/python3.11/unittest/main.py", line 127, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/local/lib/python3.11/unittest/main.py", line 247, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/usr/local/lib/python3.11/unittest/main.py", line 157, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/unittest/loader.py", line 320, in discover
    raise ImportError('Start directory is not importable: %r' % start_dir)
ImportError: Start directory is not importable: '/home/developer/src/loopback/python/tests'

developer:loopback > pwd
/home/developer/src/loopback
developer:loopback > tree
.
├── README
├── load-dir
│   └── loopback.fxs
├── package-meta-data.xml
├── python
│   ├── loopback
│   │   ├── __init__.py
│   │   └── loopback.py
│   └── tests
│       └── loopback_test.py
├── src
│   ├── Makefile
│   └── yang
│       └── loopback.yang
└── templates
    └── loopback-template.xml

7 directories, 9 files
developer:loopback > 
```

**Comment by bdolenc** [comment]
Fixed, added __init__.py to tests folder, renamed the loopback_test.py to test_loopback.py.
